// @tsm fixed: negative -22 ERROR_$COUNT
export const 
    ERROR_$COUNT = -22,
    ERROR_DECORATOR_UNKNOWN_CHILD = -1,
    ERROR_ATTRIBUTES_REQUIRED = -2,
    ERROR_DESERIALISER_GPB128_TOO_BIG = -3,
    ERROR_TSON_IMPROPER_IDENTIFIER = -4,

    ERROR_PREPARE_ARRAY_CREATOR_ALREADY_EXISTS = -5,
    ERROR_PREPARE_ARRAY_SETTER_ALREADY_EXISTS = -6,
    ERROR_PREPARE_ARRAY_GETTER_ALREADY_EXISTS = -7,
    ERROR_PREPARE_ARRAY_CANT_REMOVE_NOT_A_CHILD = -8,

    ERROR_FE_CREATE_WEBSOCKET_IMPROPER_PUSHPOINTID = -9,
    ERROR_FE_CREATE_WEBSOCKET_STATUS_CHANGE_ALREADY_EXIST = -10,
    ERROR_FE_CREATE_WEBSOCKET_STAGE_CHANGE_ALREADY_EXIST = -11,
    ERROR_FE_CREATE_WEBSOCKET_REQRES_TIMEOUT = -12,
    
    ERROR_BE_CREATE_WEBSOCKET_ON_CONNECTION_ALREADY_EXIST = -13,
    ERROR_BE_CREATE_WEBSOCKET_ON_CLOSE_ALREADY_EXIST = -14,
    ERROR_BE_CREATE_WEBSOCKET_ON_ERROR_ALREADY_EXIST = -15,
    ERROR_BE_CREATE_WEBSOCKET_IMPROPER_PUSHPOINTID = -16,
    ERROR_BE_CREATE_WEBSOCKET_WEBSOCKET_PROBLEM = -17,
    ERROR_BE_CREATE_WEBSOCKET_INVALID_TSON = -18,
    ERROR_BE_CREATE_WEBSOCKET_IMPROPER_REQUEST_FORMAT = -19,
    ERROR_BE_CREATE_WEBSOCKET_NON_EXISTING_ENDPOINT = -20,
    ERROR_BE_CREATE_WEBSOCKET_INVALID_MESSAGE_DATA = -21;

